{% set version = "1.7.1" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Sphinx/Sphinx-{{ version }}.tar.gz
  sha256: da987de5fcca21a4acc7f67a86a363039e67ac3e8827161e61b91deb131c0ee8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - jinja2
    - pygments
    - docutils
    - snowballstemmer
    - babel
    - alabaster
    - imagesize
    - requests
    - colorama  # [win]
    - typing
    - sphinxcontrib-websupport
    - packaging

test:
  commands:
    - sphinx-quickstart --version

about:
  home: http://www.sphinx-doc.org
  license: BSD 2-clause
  summary: 'Sphinx is a tool that makes it easy to create intelligent and beautiful documentation'
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: http://www.sphinx-doc.org/en/stable/contents.html
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
