{% set version = "1.7.5" %}

package:
  name: sphinx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/Sphinx/Sphinx-{{ version }}.tar.gz
  sha256: d45480a229edf70d84ca9fae3784162b1bc75ee47e480ffe04a4b7f21a95d76d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - sphinx-build = sphinx.cmd.build:main
    - sphinx-quickstart = sphinx.cmd.quickstart:main
    - sphinx-apidoc = sphinx.ext.apidoc:main
    - sphinx-autogen = sphinx.ext.autosummary.generate:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - six >=1.5
    - jinja2 >=2.3
    - pygments >2.0
    - docutils >=0.11
    - snowballstemmer >=1.1
    - babel >=1.3,!=2.0
    - alabaster >=0.7,<0.8
    - imagesize
    - requests >2.0.0
    - packaging
    - sphinxcontrib-websupport
    - colorama >=0.3.5  # [win]
    - typing  # [py27]

test:
  commands:
    - sphinx-build -h
    - sphinx-quickstart --version
    - sphinx-quickstart -h
    - sphinx-apidoc -h
    - sphinx-autogen -h
  imports:
    - sphinx
    - sphinx.pycode

about:
  home: http://www.sphinx-doc.org
  license: BSD 2-clause
  license_file: LICENSE
  summary: 'Sphinx is a tool that makes it easy to create intelligent and beautiful documentation'
  description: |
    Sphinx is a tool that makes it easy to create intelligent and beautiful documentation,
    written by Georg Brandl and licensed under the BSD license.
    It was originally created for the new Python documentation, and it has excellent
    facilities for the documentation of Python projects, but C/C++ is already supported
    as well, and it is planned to add special support for other languages as well.
  doc_url: http://www.sphinx-doc.org/en/stable/contents.html
  doc_source_url: https://github.com/sphinx-doc/sphinx/blob/master/doc/contents.rst
  dev_url: https://github.com/sphinx-doc/sphinx

extra:
  recipe-maintainers:
    - chohner
    - jakirkham
