travis:
  secure:
    BINSTAR_TOKEN: IUrtQmcQyoOwbN6gxtpBrDQv2Z2Y9ppRN/FsZsEEoD2dx1BnBVuxu70mm0VHdmWMCPSBj1m/RPt1FEWTr+07kDm2pff+h/ioRb9BEiNE5FVq26fzSbAWXYw4iP5/4jwgvD6clMzhxbJN7NYc+G3PRccoKhgpN8IhZ7VGZmzHubPBfBJOA7pWP4CGAXu8sOnsZZf+8Wy2qhjLMkJaj9FSOeAWs0ffUPlG41qiBrc94pn/y81sBTFrV5Vu3shoJu8oewzkCNmuONa+6dOAi+pdfWY3k8nTRY6G/1sj5NdRiod4F20nnecg6sPvAP/QM8auqXY0rIFxbfoHTyzlF/sPkfyZze6ETblQrfSkaZiboah3OFIL1S4VoVANqauSZu82XgdT7VDvuHrwjpJLQE14E3IRpCb2I9i8Zg39syKnbLTbRmPu3VJaYOHgDyzL+Q5Wr3MBbi4ARF8d6NcBdqVdGV0FmZ5z6aFKcGqVmGLWNs1rJmTRa0lQaKZ/qi+CvJxRGqo85f565JW94eOyTydXI0F3gXQpY+N0BbQ7Hr7nX4MTeUKHYjzDVHNYxXi2tOOKHiLorEDDQwnv2FhbkLc97jteFWQXz1gVZEOOEM1mE5SH1nLRDqQwJaUdecHmkJ3PZcK/TF4Kdu+0QtCXK8voayOzqfwlfPzZJTrY90lOt54=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
