travis:
  secure:
    BINSTAR_TOKEN: qX97bTRes6QEoh0uhvbqtJkCd2xMSeBJ99IL+bkkQXHJdVTq0Vv0GluEwXE3BJ/5+39Lb5FjKnMYjJ7okz/0Au5MqHcP4016KPmvn0yRbxyvdQGQzZnsPdLjS+ubbtQ33/c2xQE/szUmG+ybhAxFL2+da48uydfSCNyQvVCD6l5yJ9rG1ZubYLnkgbCMjlR8wGMZGxPDcgDIs/iQzg1mw2P3b/I5BstiUm2MK62SVvwm4rXgx/8CsStTStA+FVS784x71UG7ldsC+WDiKXk0GYY3K0/IQE0qmPuoDVjDFWkIsbeaL17qJ86xsaZTxzzejEPIMlmjHjIVRKm2Pc1bqm/zGjIBi5baY//BoGd3x1T/C3UsGiZz9qyfXmzzr+ylp4OoALL5Rc9AnHPKtagLa8oBxY05c7IRUMv9G91FCTsthFqL8ELg7go9srHEFUOSGsGQmsX4QDwYaNLnntTUCBQcVISv2jIQaIAAAoK/5/6mCzWgottdKpOhWroNovCOPuHTB2U8j+zqOjab2eoyKzdnFspIJ4wMNrPlMbWz+Sued3F9MYL7zdHFZsYPmhj8UO2k/clR2DBDKgBvWsmAqkrmNHWzumx8lu84kI+hZzv7+BilKcN6nZXcQcyarmWleiQxkUKrynA5OVbNeBAMuB2CJGIX7GW46dLKxpMwbLM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
